### ISSUE TITLE
Set tokens in cookies improvement [ help needed ]

### ISSUE THREAD

**Issue by Aetherall** [accounts-js/rest#27]
Hi! I need, for my project to use cookie based token storage.
Indeed, I want to be able to authenticate the user in the first request, so I can achieve SSR with restricted data.

How do you recommand to edit the rest API in order to do so?

I was thinking about turning this : 
```javascript
res.json(objectContainingTokens)
```
into this : 
```javascript
res.Cookie('access-token', tokens.accessToken, {httpOnly:true, secure:true, maxAge:172800} )
res.Cookie('refresh-token', tokens.refreshToken, {httpOnly:true, secure:true, maxAge:1296000000} )
res.json(objectWithoutTokens)
```

Which other package will I need To edit?

Thank you

**Comment by davidyaha** [comment]
This looks good to me but I would love to have it as optional addition to the current storage.
Also this should maybe be implemented under the accounts server in some way so we can use the same mechanism for graphql interface as well.

One last thing is we should consider sending only the access-token as cookie so it will be expired faster? or the other way? no sure about but I think we have an open issue on the subject at js-accounts/accounts
